name: Validate Node package version

description: Validate the version number in package.json and package-lock.json against the git tag

inputs:
  package-json-location:
    description: The location of the package.json file to validate
    required: false
    default: ./package.json
  package-lock-json-location:
    description: The location of the package-lock.json file to validate
    required: false
    default: ./package-lock.json

runs:
  using: "composite"
  steps:
    - name: Get version from git tag
      id: get_version_from_git_tag
      uses: ./.github/actions/version

    - name: Validate
      env:
        INPUTS_PACKAGE_JSON_LOCATION: ${{ inputs.package-json-location }}
        INPUTS_PACKAGE_LOCK_JSON_LOCATION: ${{ inputs.package-lock-json-location }}
        GIT_TAG_VERSION: ${{ steps.get_version_from_git_tag.outputs.version }}
      run: |
        # Get the version from package.json and package-lock.json using Node
        CURRENT_VERSION=$(node -p "require('${INPUTS_PACKAGE_JSON_LOCATION}').version")
        PACKAGE_LOCK_VERSION=$(node -p "require('${INPUTS_PACKAGE_LOCK_JSON_LOCATION}').version")

        echo "Version in package.json:        ${CURRENT_VERSION}"
        echo "Version in package-lock.json:   ${PACKAGE_LOCK_VERSION}"
        echo "Version to check against:       ${GIT_TAG_VERSION}"

        [[ "${CURRENT_VERSION}" == "${PACKAGE_LOCK_VERSION}" ]] || (echo "Version ${CURRENT_VERSION} in package.json doesn't match version ${PACKAGE_LOCK_VERSION} in package-lock.json." && exit 1)

        [[ "${CURRENT_VERSION}" == "${GIT_TAG_VERSION}" ]] || (echo "The git tag ${GIT_TAG_VERSION} doesn't match the version in package.json." && exit 1)
      shell: bash
