name: Validate Node package version

description: Validate the version number in package.json and package-lock.json against the git tag

inputs:
  package-json-location:
    description: The location of the package.json file to validate
    required: false
    default: ./package.json
  package-lock-json-location:
    description: The location of the package-lock.json file to validate
    required: false
    default: ./package-lock.json

runs:
  using: "composite"
  steps:
    - name: DEBUG
      run: |
        echo "INPUTS_PACKAGE_JSON_LOCATION:      ${INPUTS_PACKAGE_JSON_LOCATION}"
        echo "INPUTS_PACKAGE_LOCK_JSON_LOCATION: ${INPUTS_PACKAGE_LOCK_JSON_LOCATION}"
        echo "GITHUB_ACTION_PATH:                ${GITHUB_ACTION_PATH}"
        echo "GITHUB_ACTION_REPOSITORY:          ${GITHUB_ACTION_REPOSITORY}"
      shell: bash

    - name: Get version from git tag
      id: version
      uses: nationalarchives/github-actions/.github/actions/version@main # zizmor: ignore[unpinned-uses] Owned by The National Archives

    - name: Validate
      env:
        INPUTS_PACKAGE_JSON_LOCATION: ${{ inputs.package-json-location }}
        INPUTS_PACKAGE_LOCK_JSON_LOCATION: ${{ inputs.package-lock-json-location }}
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        # Get the version from package.json and package-lock.json using Node
        PACKAGE_VERSION=$(node -p "require('${INPUTS_PACKAGE_JSON_LOCATION}').version")
        PACKAGE_LOCK_VERSION=$(node -p "require('${INPUTS_PACKAGE_LOCK_JSON_LOCATION}').version")

        echo "package.json version:      ${PACKAGE_VERSION}"
        echo "package-lock.json version: ${PACKAGE_LOCK_VERSION}"
        echo "Version to check against:  ${VERSION}"

        [[ "${PACKAGE_VERSION}" == "${PACKAGE_LOCK_VERSION}" ]] || (echo "Version ${PACKAGE_VERSION} in package.json doesn't match version ${PACKAGE_LOCK_VERSION} in package-lock.json." && exit 1)

        [[ "${PACKAGE_VERSION}" == "${VERSION}" ]] || (echo "The branch/tag version ${VERSION} doesn't match version ${PACKAGE_VERSION} in package.json." && exit 1)
      shell: bash
